import pandas as pd
import os
from typing import Dict

def blend_smart_weighted(submission_dir: str, report_path: str, output_path: str):
    """
    reads the model_report.html to find AUC scores
    calculates weights proportional to (AUC - baseline)
    generates the ultimate weighted final submission
    """
    if not os.path.exists(report_path):
        print("Model report not found. Defaulting to equal weights.")
        return
        
    # Extract results from the HTML report (assuming it was generated by our dashboard.py)
    # We use pandas read_html to scrape our own generated table
    tables = pd.read_html(report_path)
    report_df = tables[0]
    
    # Calculate weights based on AUC performance above a 0.5 baseline
    # Higher AUC = Exponentially higher weight
    report_df['weight'] = (report_df['auc'] - 0.5) ** 2
    weights = dict(zip(report_df['model'], report_df['weight']))
    
    sub_files = [f for f in os.listdir(submission_dir) if f.endswith('.csv') and 'blended' not in f]
    blended_df = None
    total_weight = 0.0

    for file in sub_files:
        model_name = file.replace('_submission.csv', '')
        weight = weights.get(model_name, 0.0) # 0 weight if model didn't make the report
        
        df = pd.read_csv(os.path.join(submission_dir, file))
        if blended_df is None:
            blended_df = df.copy()
            blended_df['smoking'] = df['smoking'] * weight
        else:
            blended_df['smoking'] += df['smoking'] * weight
        total_weight += weight

    blended_df['smoking'] /= total_weight
    blended_df.to_csv(output_path, index=False)
    print(f"🏆 Smart Blended Submission saved: {output_path}")

if __name__ == "__main__":
    blend_smart_weighted(
        "data/processed/submissions", 
        "data/processed/model_report.html", 
        "data/processed/submissions/blended_final_submission.csv"
    )
